name: "Python Container Action Template"
description: "Get started with Python Container actions"
author: "Alex Grönholm"
inputs:
  path:
    description: Path to the changelog file
    required: true
  version_pattern:
    description: Regular expression to use to detect where a version entry begins and ends
    default: "^\\*\\*([0-9][^*]*)\\*\\*"
  header:
    description: >
      Text to prepend to the beginning of the generated changelog (in the same format as
      the changelog itself)
  footer:
    description: >
      Text to append to the end of the generated changelog (in the same format as the
      changelog itself)
outputs:
  changelog:
    description: The generated changelog text in the Markdown format
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: file-text
